export const regions = [
  { id: "reg-us", name: "United States", code: "US" },
  { id: "reg-eu", name: "European Union", code: "EU" },
  { id: "reg-apac", name: "Asia Pacific", code: "APAC" },
  { id: "reg-cn", name: "China", code: "CN" },
  { id: "reg-jp", name: "Japan", code: "JP" },
  { id: "reg-in", name: "India", code: "IN" },
];

export const facilities = [
  { id: "fac-austin", name: "Austin Assembly Plant", type: "Assembly" },
  { id: "fac-munich", name: "Munich EV Campus", type: "Manufacturing" },
  { id: "fac-shenzhen", name: "Shenzhen Smart Device Hub", type: "Assembly" },
  { id: "fac-pune", name: "Pune Industrial Park", type: "Manufacturing" },
  { id: "fac-osaka", name: "Osaka Precision Works", type: "Component" },
  { id: "fac-dallas", name: "Dallas Medical Devices", type: "Cleanroom" },
  { id: "fac-rotterdam", name: "Rotterdam Logistics Hub", type: "Distribution" },
  { id: "fac-seoul", name: "Seoul Semiconductor Fab", type: "Fabrication" },
];

export const suppliers = [
  { id: "sup-001", name: "NovaChip Systems", tier: "Tier 1", reliabilityScore: 0.94, regionId: "reg-us" },
  { id: "sup-002", name: "Pacific Microelectronics", tier: "Tier 1", reliabilityScore: 0.91, regionId: "reg-jp" },
  { id: "sup-003", name: "Dragon Battery Co.", tier: "Tier 1", reliabilityScore: 0.88, regionId: "reg-cn" },
  { id: "sup-004", name: "EuroPower Cells", tier: "Tier 2", reliabilityScore: 0.86, regionId: "reg-eu" },
  { id: "sup-005", name: "BrightDisplay Ltd.", tier: "Tier 1", reliabilityScore: 0.9, regionId: "reg-apac" },
  { id: "sup-006", name: "Apex Sensors", tier: "Tier 2", reliabilityScore: 0.87, regionId: "reg-us" },
  { id: "sup-007", name: "Silicon Valley PCB", tier: "Tier 2", reliabilityScore: 0.89, regionId: "reg-us" },
  { id: "sup-008", name: "Global Connectors Inc.", tier: "Tier 3", reliabilityScore: 0.82, regionId: "reg-in" },
  { id: "sup-009", name: "Precision Chassis Works", tier: "Tier 2", reliabilityScore: 0.85, regionId: "reg-eu" },
  { id: "sup-010", name: "Quantum Firmware Labs", tier: "Tier 1", reliabilityScore: 0.93, regionId: "reg-us" },
  { id: "sup-011", name: "Himalaya Rare Metals", tier: "Tier 2", reliabilityScore: 0.8, regionId: "reg-in" },
  { id: "sup-012", name: "Tokyo Optics", tier: "Tier 1", reliabilityScore: 0.92, regionId: "reg-jp" },
  { id: "sup-013", name: "Shanghai Motor Drives", tier: "Tier 1", reliabilityScore: 0.87, regionId: "reg-cn" },
  { id: "sup-014", name: "Nordic Thermal Systems", tier: "Tier 2", reliabilityScore: 0.84, regionId: "reg-eu" },
  { id: "sup-015", name: "Bay Area AI Modules", tier: "Tier 1", reliabilityScore: 0.95, regionId: "reg-us" },
  { id: "sup-016", name: "Chennai Fasteners", tier: "Tier 3", reliabilityScore: 0.79, regionId: "reg-in" },
  { id: "sup-017", name: "Kyoto Memory Foundry", tier: "Tier 1", reliabilityScore: 0.96, regionId: "reg-jp" },
  { id: "sup-018", name: "Guangzhou Display Tech", tier: "Tier 2", reliabilityScore: 0.83, regionId: "reg-cn" },
  { id: "sup-019", name: "Alpine Safety Systems", tier: "Tier 2", reliabilityScore: 0.88, regionId: "reg-eu" },
  { id: "sup-020", name: "Redwood Biomed Parts", tier: "Tier 1", reliabilityScore: 0.91, regionId: "reg-us" },
  { id: "sup-021", name: "Seoul Power IC", tier: "Tier 1", reliabilityScore: 0.9, regionId: "reg-apac" },
  { id: "sup-022", name: "Mumbai Cable Harness", tier: "Tier 3", reliabilityScore: 0.81, regionId: "reg-in" },
  { id: "sup-023", name: "Osaka Camera Modules", tier: "Tier 1", reliabilityScore: 0.93, regionId: "reg-jp" },
  { id: "sup-024", name: "Berlin EV Inverters", tier: "Tier 1", reliabilityScore: 0.89, regionId: "reg-eu" },
  { id: "sup-025", name: "Shenzhen IoT Boards", tier: "Tier 2", reliabilityScore: 0.86, regionId: "reg-cn" },
];

export const components = [
  { id: "cmp-001", name: "A17 Neural Processor", category: "Semiconductor", critical: true },
  { id: "cmp-002", name: "LPDDR5X Memory Stack", category: "Semiconductor", critical: true },
  { id: "cmp-003", name: "OLED Display Panel 6.7in", category: "Display", critical: true },
  { id: "cmp-004", name: "Lithium Polymer Cell 5000mAh", category: "Battery", critical: true },
  { id: "cmp-005", name: "5G RF Front-End Module", category: "Semiconductor", critical: true },
  { id: "cmp-006", name: "IMU Motion Sensor", category: "Sensor", critical: false },
  { id: "cmp-007", name: "Aluminum Unibody Frame", category: "Chassis", critical: false },
  { id: "cmp-008", name: "USB-C Power Controller", category: "Semiconductor", critical: true },
  { id: "cmp-009", name: "Multi-layer Mainboard PCB", category: "PCB", critical: true },
  { id: "cmp-010", name: "Secure Boot Firmware", category: "Firmware", critical: true },
  { id: "cmp-011", name: "48MP Camera Module", category: "Optics", critical: false },
  { id: "cmp-012", name: "Thermal Graphite Sheet", category: "Thermal", critical: false },
  { id: "cmp-013", name: "EV Drive Inverter", category: "Power Electronics", critical: true },
  { id: "cmp-014", name: "NMC Battery Pack 75kWh", category: "Battery", critical: true },
  { id: "cmp-015", name: "LiDAR Range Sensor", category: "Sensor", critical: true },
  { id: "cmp-016", name: "ADAS Compute Module", category: "Semiconductor", critical: true },
  { id: "cmp-017", name: "Steel Chassis Platform", category: "Chassis", critical: false },
  { id: "cmp-018", name: "DC Fast Charge Port", category: "Connector", critical: true },
  { id: "cmp-019", name: "Autonomous Driving Firmware", category: "Firmware", critical: true },
  { id: "cmp-020", name: "Cabin HVAC Controller", category: "Electronics", critical: false },
  { id: "cmp-021", name: "IoT WiFi/BLE Combo Chip", category: "Semiconductor", critical: true },
  { id: "cmp-022", name: "Environmental Sensor Array", category: "Sensor", critical: false },
  { id: "cmp-023", name: "Miniature Li-ion Cell", category: "Battery", critical: true },
  { id: "cmp-024", name: "Injection Molded Enclosure", category: "Chassis", critical: false },
  { id: "cmp-025", name: "Edge ML Firmware", category: "Firmware", critical: true },
  { id: "cmp-026", name: "Medical Grade Power Supply", category: "Power Electronics", critical: true },
  { id: "cmp-027", name: "Pulse Oximetry Sensor", category: "Sensor", critical: true },
  { id: "cmp-028", name: "Biocompatible Housing", category: "Chassis", critical: false },
  { id: "cmp-029", name: "Patient Monitoring PCB", category: "PCB", critical: true },
  { id: "cmp-030", name: "FDA Validated Firmware", category: "Firmware", critical: true },
  { id: "cmp-031", name: "Laptop CPU Die", category: "Semiconductor", critical: true },
  { id: "cmp-032", name: "NVMe SSD Controller", category: "Semiconductor", critical: true },
  { id: "cmp-033", name: "14in LCD Panel", category: "Display", critical: true },
  { id: "cmp-034", name: "Laptop Battery 99Wh", category: "Battery", critical: true },
  { id: "cmp-035", name: "Keyboard Flex PCB", category: "PCB", critical: false },
  { id: "cmp-036", name: "Magnesium Alloy Shell", category: "Chassis", critical: false },
  { id: "cmp-037", name: "WiFi 7 Radio Module", category: "Semiconductor", critical: true },
  { id: "cmp-038", name: "GPU Accelerator Die", category: "Semiconductor", critical: true },
  { id: "cmp-039", name: "HBM Memory Stack", category: "Semiconductor", critical: true },
  { id: "cmp-040", name: "Liquid Cooling Plate", category: "Thermal", critical: false },
  { id: "cmp-041", name: "Power Management IC", category: "Semiconductor", critical: true },
  { id: "cmp-042", name: "E-ink Display Driver", category: "Display", critical: false },
  { id: "cmp-043", name: "GNSS Positioning Module", category: "Semiconductor", critical: false },
  { id: "cmp-044", name: "Waterproof Seal Gasket", category: "Mechanical", critical: false },
  { id: "cmp-045", name: "High Voltage Junction Box", category: "Power Electronics", critical: true },
  { id: "cmp-046", name: "Regenerative Brake Controller", category: "Electronics", critical: true },
  { id: "cmp-047", name: "Telematics Modem", category: "Semiconductor", critical: false },
  { id: "cmp-048", name: "Smartwatch SoC", category: "Semiconductor", critical: true },
  { id: "cmp-049", name: "Heart Rate Optical Sensor", category: "Sensor", critical: true },
  { id: "cmp-050", name: "1.9in AMOLED Display", category: "Display", critical: true },
  { id: "cmp-051", name: "Smartwatch Battery 450mAh", category: "Battery", critical: true },
  { id: "cmp-052", name: "Sapphire Crystal Lens", category: "Optics", critical: false },
  { id: "cmp-053", name: "UWB Radio Chip", category: "Semiconductor", critical: false },
  { id: "cmp-054", name: "Enterprise SSD NAND", category: "Semiconductor", critical: true },
  { id: "cmp-055", name: "Rack Power Distribution Unit", category: "Power Electronics", critical: true },
  { id: "cmp-056", name: "Data Center Cooling Fan", category: "Thermal", critical: false },
  { id: "cmp-057", name: "Backup BMS Controller", category: "Electronics", critical: true },
  { id: "cmp-058", name: "Alternate RF Module", category: "Semiconductor", critical: true },
  { id: "cmp-059", name: "Alternate OLED Panel", category: "Display", critical: true },
  { id: "cmp-060", name: "Alternate EV Inverter", category: "Power Electronics", critical: true },
];

export const products = [
  { id: "prd-001", name: "NovaPhone X Pro", sku: "NPX-100", line: "Smartphone", facilityId: "fac-shenzhen" },
  { id: "prd-002", name: "NovaPhone X Lite", sku: "NPX-110", line: "Smartphone", facilityId: "fac-shenzhen" },
  { id: "prd-003", name: "Velocity EV Sedan", sku: "VES-200", line: "Electric Vehicle", facilityId: "fac-munich" },
  { id: "prd-004", name: "Velocity EV SUV", sku: "VES-210", line: "Electric Vehicle", facilityId: "fac-munich" },
  { id: "prd-005", name: "HomeGuard Hub", sku: "HGH-300", line: "IoT", facilityId: "fac-austin" },
  { id: "prd-006", name: "ClimateSense Node", sku: "CSN-310", line: "IoT", facilityId: "fac-austin" },
  { id: "prd-007", name: "VitalTrack Monitor", sku: "VTM-400", line: "Medical", facilityId: "fac-dallas" },
  { id: "prd-008", name: "VitalTrack Patch", sku: "VTP-410", line: "Medical", facilityId: "fac-dallas" },
  { id: "prd-009", name: "ProBook Ultra 14", sku: "PBU-500", line: "Laptop", facilityId: "fac-pune" },
  { id: "prd-010", name: "ProBook Workstation 16", sku: "PBW-510", line: "Laptop", facilityId: "fac-pune" },
  { id: "prd-011", name: "RenderStation A800", sku: "RSA-600", line: "Workstation", facilityId: "fac-austin" },
  { id: "prd-012", name: "PulseBand Active", sku: "PBA-700", line: "Wearable", facilityId: "fac-osaka" },
  { id: "prd-013", name: "PulseBand Health", sku: "PBH-710", line: "Wearable", facilityId: "fac-osaka" },
  { id: "prd-014", name: "FleetTrack Telematics", sku: "FTT-800", line: "Automotive", facilityId: "fac-rotterdam" },
  { id: "prd-015", name: "EdgeServe R240", sku: "ESR-900", line: "Data Center", facilityId: "fac-seoul" },
  { id: "prd-016", name: "AgriSense Probe", sku: "ASP-320", line: "IoT", facilityId: "fac-austin" },
  { id: "prd-017", name: "NovaPhone X Fold", sku: "NPX-120", line: "Smartphone", facilityId: "fac-shenzhen" },
  { id: "prd-018", name: "Velocity EV Truck", sku: "VES-220", line: "Electric Vehicle", facilityId: "fac-munich" },
  { id: "prd-019", name: "SmartCity Air Node", sku: "SCA-330", line: "IoT", facilityId: "fac-austin" },
  { id: "prd-020", name: "VitalTrack ICU Hub", sku: "VTI-420", line: "Medical", facilityId: "fac-dallas" },
];

type SupplyLink = {
  supplierId: string;
  componentId: string;
  unitCost: number;
  leadTimeDays: number;
  minOrderQty: number;
};

type UsedInLink = {
  componentId: string;
  productId: string;
  quantity: number;
  isCriticalPath: boolean;
};

type DependsOnLink = {
  parentId: string;
  childId: string;
  quantity: number;
};

type AlternativeLink = {
  componentA: string;
  componentB: string;
  compatibilityScore: number;
};

export const supplyLinks: SupplyLink[] = [
  { supplierId: "sup-015", componentId: "cmp-001", unitCost: 89, leadTimeDays: 21, minOrderQty: 5000 },
  { supplierId: "sup-017", componentId: "cmp-002", unitCost: 34, leadTimeDays: 14, minOrderQty: 10000 },
  { supplierId: "sup-005", componentId: "cmp-003", unitCost: 72, leadTimeDays: 28, minOrderQty: 2000 },
  { supplierId: "sup-003", componentId: "cmp-004", unitCost: 18, leadTimeDays: 10, minOrderQty: 5000 },
  { supplierId: "sup-001", componentId: "cmp-005", unitCost: 12, leadTimeDays: 35, minOrderQty: 8000 },
  { supplierId: "sup-006", componentId: "cmp-006", unitCost: 3.5, leadTimeDays: 7, minOrderQty: 20000 },
  { supplierId: "sup-009", componentId: "cmp-007", unitCost: 22, leadTimeDays: 18, minOrderQty: 1000 },
  { supplierId: "sup-021", componentId: "cmp-008", unitCost: 4.2, leadTimeDays: 12, minOrderQty: 15000 },
  { supplierId: "sup-007", componentId: "cmp-009", unitCost: 15, leadTimeDays: 9, minOrderQty: 3000 },
  { supplierId: "sup-010", componentId: "cmp-010", unitCost: 2, leadTimeDays: 5, minOrderQty: 1 },
  { supplierId: "sup-023", componentId: "cmp-011", unitCost: 28, leadTimeDays: 16, minOrderQty: 4000 },
  { supplierId: "sup-014", componentId: "cmp-012", unitCost: 1.8, leadTimeDays: 6, minOrderQty: 25000 },
  { supplierId: "sup-024", componentId: "cmp-013", unitCost: 420, leadTimeDays: 45, minOrderQty: 500 },
  { supplierId: "sup-003", componentId: "cmp-014", unitCost: 6800, leadTimeDays: 60, minOrderQty: 100 },
  { supplierId: "sup-006", componentId: "cmp-015", unitCost: 190, leadTimeDays: 30, minOrderQty: 800 },
  { supplierId: "sup-015", componentId: "cmp-016", unitCost: 310, leadTimeDays: 42, minOrderQty: 600 },
  { supplierId: "sup-009", componentId: "cmp-017", unitCost: 950, leadTimeDays: 25, minOrderQty: 200 },
  { supplierId: "sup-008", componentId: "cmp-018", unitCost: 45, leadTimeDays: 14, minOrderQty: 2000 },
  { supplierId: "sup-010", componentId: "cmp-019", unitCost: 5, leadTimeDays: 8, minOrderQty: 1 },
  { supplierId: "sup-014", componentId: "cmp-020", unitCost: 65, leadTimeDays: 20, minOrderQty: 500 },
  { supplierId: "sup-025", componentId: "cmp-021", unitCost: 6.5, leadTimeDays: 11, minOrderQty: 12000 },
  { supplierId: "sup-006", componentId: "cmp-022", unitCost: 8, leadTimeDays: 9, minOrderQty: 8000 },
  { supplierId: "sup-004", componentId: "cmp-023", unitCost: 4, leadTimeDays: 7, minOrderQty: 30000 },
  { supplierId: "sup-016", componentId: "cmp-024", unitCost: 2.5, leadTimeDays: 10, minOrderQty: 50000 },
  { supplierId: "sup-010", componentId: "cmp-025", unitCost: 1.5, leadTimeDays: 4, minOrderQty: 1 },
  { supplierId: "sup-020", componentId: "cmp-026", unitCost: 120, leadTimeDays: 22, minOrderQty: 300 },
  { supplierId: "sup-020", componentId: "cmp-027", unitCost: 35, leadTimeDays: 18, minOrderQty: 1500 },
  { supplierId: "sup-019", componentId: "cmp-028", unitCost: 18, leadTimeDays: 15, minOrderQty: 2000 },
  { supplierId: "sup-007", componentId: "cmp-029", unitCost: 22, leadTimeDays: 12, minOrderQty: 1000 },
  { supplierId: "sup-010", componentId: "cmp-030", unitCost: 8, leadTimeDays: 6, minOrderQty: 1 },
  { supplierId: "sup-015", componentId: "cmp-031", unitCost: 210, leadTimeDays: 28, minOrderQty: 2000 },
  { supplierId: "sup-017", componentId: "cmp-032", unitCost: 45, leadTimeDays: 16, minOrderQty: 5000 },
  { supplierId: "sup-018", componentId: "cmp-033", unitCost: 95, leadTimeDays: 24, minOrderQty: 1500 },
  { supplierId: "sup-004", componentId: "cmp-034", unitCost: 55, leadTimeDays: 14, minOrderQty: 3000 },
  { supplierId: "sup-007", componentId: "cmp-035", unitCost: 6, leadTimeDays: 8, minOrderQty: 4000 },
  { supplierId: "sup-009", componentId: "cmp-036", unitCost: 48, leadTimeDays: 20, minOrderQty: 800 },
  { supplierId: "sup-002", componentId: "cmp-037", unitCost: 14, leadTimeDays: 18, minOrderQty: 6000 },
  { supplierId: "sup-015", componentId: "cmp-038", unitCost: 980, leadTimeDays: 56, minOrderQty: 300 },
  { supplierId: "sup-017", componentId: "cmp-039", unitCost: 420, leadTimeDays: 40, minOrderQty: 400 },
  { supplierId: "sup-014", componentId: "cmp-040", unitCost: 35, leadTimeDays: 12, minOrderQty: 600 },
  { supplierId: "sup-021", componentId: "cmp-041", unitCost: 3.8, leadTimeDays: 10, minOrderQty: 20000 },
  { supplierId: "sup-012", componentId: "cmp-042", unitCost: 7, leadTimeDays: 15, minOrderQty: 5000 },
  { supplierId: "sup-001", componentId: "cmp-043", unitCost: 9, leadTimeDays: 11, minOrderQty: 7000 },
  { supplierId: "sup-016", componentId: "cmp-044", unitCost: 0.8, leadTimeDays: 5, minOrderQty: 100000 },
  { supplierId: "sup-024", componentId: "cmp-045", unitCost: 180, leadTimeDays: 30, minOrderQty: 400 },
  { supplierId: "sup-013", componentId: "cmp-046", unitCost: 95, leadTimeDays: 22, minOrderQty: 700 },
  { supplierId: "sup-001", componentId: "cmp-047", unitCost: 22, leadTimeDays: 14, minOrderQty: 3000 },
  { supplierId: "sup-002", componentId: "cmp-048", unitCost: 18, leadTimeDays: 16, minOrderQty: 8000 },
  { supplierId: "sup-012", componentId: "cmp-049", unitCost: 6, leadTimeDays: 9, minOrderQty: 15000 },
  { supplierId: "sup-005", componentId: "cmp-050", unitCost: 14, leadTimeDays: 12, minOrderQty: 10000 },
  { supplierId: "sup-004", componentId: "cmp-051", unitCost: 3, leadTimeDays: 8, minOrderQty: 25000 },
  { supplierId: "sup-012", componentId: "cmp-052", unitCost: 11, leadTimeDays: 20, minOrderQty: 5000 },
  { supplierId: "sup-002", componentId: "cmp-053", unitCost: 5, leadTimeDays: 10, minOrderQty: 12000 },
  { supplierId: "sup-017", componentId: "cmp-054", unitCost: 88, leadTimeDays: 21, minOrderQty: 4000 },
  { supplierId: "sup-011", componentId: "cmp-055", unitCost: 240, leadTimeDays: 28, minOrderQty: 200 },
  { supplierId: "sup-014", componentId: "cmp-056", unitCost: 12, leadTimeDays: 7, minOrderQty: 5000 },
  { supplierId: "sup-013", componentId: "cmp-057", unitCost: 75, leadTimeDays: 18, minOrderQty: 900 },
  // Alternate suppliers for some components (not sole source)
  { supplierId: "sup-002", componentId: "cmp-002", unitCost: 36, leadTimeDays: 18, minOrderQty: 8000 },
  { supplierId: "sup-018", componentId: "cmp-003", unitCost: 68, leadTimeDays: 22, minOrderQty: 2500 },
  { supplierId: "sup-004", componentId: "cmp-004", unitCost: 19, leadTimeDays: 12, minOrderQty: 4000 },
  { supplierId: "sup-011", componentId: "cmp-014", unitCost: 7100, leadTimeDays: 70, minOrderQty: 80 },
  { supplierId: "sup-013", componentId: "cmp-013", unitCost: 435, leadTimeDays: 50, minOrderQty: 450 },
  // Alternative component suppliers
  { supplierId: "sup-021", componentId: "cmp-058", unitCost: 13, leadTimeDays: 20, minOrderQty: 7000 },
  { supplierId: "sup-018", componentId: "cmp-059", unitCost: 70, leadTimeDays: 25, minOrderQty: 2200 },
  { supplierId: "sup-013", componentId: "cmp-060", unitCost: 410, leadTimeDays: 42, minOrderQty: 550 },
];

export const usedInLinks: UsedInLink[] = [
  { componentId: "cmp-001", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-002", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-003", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-004", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-005", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-009", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-010", productId: "prd-001", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-011", productId: "prd-001", quantity: 3, isCriticalPath: false },
  { componentId: "cmp-001", productId: "prd-002", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-002", productId: "prd-002", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-003", productId: "prd-002", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-004", productId: "prd-002", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-005", productId: "prd-002", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-001", productId: "prd-017", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-002", productId: "prd-017", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-003", productId: "prd-017", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-004", productId: "prd-017", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-005", productId: "prd-017", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-013", productId: "prd-003", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-014", productId: "prd-003", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-015", productId: "prd-003", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-016", productId: "prd-003", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-019", productId: "prd-003", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-045", productId: "prd-003", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-013", productId: "prd-004", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-014", productId: "prd-004", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-016", productId: "prd-004", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-019", productId: "prd-004", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-013", productId: "prd-018", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-014", productId: "prd-018", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-016", productId: "prd-018", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-046", productId: "prd-018", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-021", productId: "prd-005", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-023", productId: "prd-005", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-025", productId: "prd-005", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-021", productId: "prd-006", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-022", productId: "prd-006", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-023", productId: "prd-006", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-021", productId: "prd-016", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-022", productId: "prd-016", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-025", productId: "prd-016", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-021", productId: "prd-019", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-022", productId: "prd-019", quantity: 3, isCriticalPath: true },
  { componentId: "cmp-026", productId: "prd-007", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-027", productId: "prd-007", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-029", productId: "prd-007", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-030", productId: "prd-007", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-027", productId: "prd-008", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-028", productId: "prd-008", quantity: 1, isCriticalPath: false },
  { componentId: "cmp-030", productId: "prd-008", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-026", productId: "prd-020", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-027", productId: "prd-020", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-029", productId: "prd-020", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-031", productId: "prd-009", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-032", productId: "prd-009", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-033", productId: "prd-009", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-034", productId: "prd-009", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-037", productId: "prd-009", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-031", productId: "prd-010", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-038", productId: "prd-010", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-039", productId: "prd-010", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-033", productId: "prd-010", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-038", productId: "prd-011", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-039", productId: "prd-011", quantity: 4, isCriticalPath: true },
  { componentId: "cmp-040", productId: "prd-011", quantity: 1, isCriticalPath: false },
  { componentId: "cmp-048", productId: "prd-012", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-049", productId: "prd-012", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-050", productId: "prd-012", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-051", productId: "prd-012", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-048", productId: "prd-013", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-049", productId: "prd-013", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-050", productId: "prd-013", quantity: 1, isCriticalPath: true },
  { componentId: "cmp-047", productId: "prd-014", quantity: 1, isCriticalPath: false },
  { componentId: "cmp-043", productId: "prd-014", quantity: 1, isCriticalPath: false },
  { componentId: "cmp-054", productId: "prd-015", quantity: 24, isCriticalPath: true },
  { componentId: "cmp-055", productId: "prd-015", quantity: 2, isCriticalPath: true },
  { componentId: "cmp-056", productId: "prd-015", quantity: 8, isCriticalPath: false },
  { componentId: "cmp-057", productId: "prd-015", quantity: 1, isCriticalPath: true },
];

export const dependsOnLinks: DependsOnLink[] = [
  { parentId: "cmp-009", childId: "cmp-041", quantity: 4 },
  { parentId: "cmp-009", childId: "cmp-008", quantity: 2 },
  { parentId: "cmp-016", childId: "cmp-001", quantity: 2 },
  { parentId: "cmp-016", childId: "cmp-002", quantity: 4 },
  { parentId: "cmp-013", childId: "cmp-041", quantity: 6 },
  { parentId: "cmp-045", childId: "cmp-018", quantity: 2 },
  { parentId: "cmp-029", childId: "cmp-041", quantity: 3 },
  { parentId: "cmp-031", childId: "cmp-041", quantity: 2 },
  { parentId: "cmp-038", childId: "cmp-039", quantity: 8 },
  { parentId: "cmp-048", childId: "cmp-041", quantity: 1 },
  { parentId: "cmp-055", childId: "cmp-041", quantity: 2 },
];

export const alternativeLinks: AlternativeLink[] = [
  { componentA: "cmp-005", componentB: "cmp-058", compatibilityScore: 0.92 },
  { componentA: "cmp-003", componentB: "cmp-059", compatibilityScore: 0.88 },
  { componentA: "cmp-013", componentB: "cmp-060", compatibilityScore: 0.85 },
];
